name: vocab_list
description: An app to create and manage a vocabulary list.
version: 0.0.1+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  http: 0.13.5
  path_provider: 2.0.11
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
